Models/Nguoidung.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace QuanLyBanGiay_ADMIN.Models;

public partial class Nguoidung
{
    public int MaNguoidung { get; set; }
    public string? TenNguoidung { get; set; }
    public string? Gioitinh { get; set; }
    public string? SodienthoaiNv { get; set; }
    public string? DiachiNv { get; set; }
    public int? MaChucvu { get; set; }
    public string? Username { get; set; }
    public string? Password { get; set; }
   
    public virtual ICollection<DanhgiaSp> DanhgiaSps { get; set; } = new List<DanhgiaSp>();

    public virtual ICollection<Giohang> Giohangs { get; set; } = new List<Giohang>();


}

Controllers/NguoiDungController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyBanGiay_ADMIN.Data;
using QuanLyBanGiay_ADMIN.Models;
using System.Security.Cryptography.Xml;
using X.PagedList;

namespace QuanLyBanGiay_ADMIN.Controllers
{
    public class NguoiDungController : Controller
    {
        private readonly BanGiayContext context;

        public NguoiDungController(BanGiayContext context)
        {
            this.context = context;
        }
        public IActionResult Index(string TenNguoidung, int page = 1)
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.TB = da.Count();
            ViewBag.YC = da.ToList();

            var username = HttpContext.Session.GetString("tk");
            ViewBag.Username = username;
            if (TenNguoidung == null)
            {
                page = page < 1 ? 1 : page;
                int pagesize = 6;
                var data = context.ThongTinNguoiDungs.FromSqlRaw("Exec ThongTin_NguoiDung").ToList().ToPagedList(page, pagesize);
                return View(data);
            }
            else
            {
                ViewBag.TenND = TenNguoidung.ToString();
                page = page < 1 ? 1 : page;
                int pagesize = 6;
                var data = context.TimKiem_NguoiDung(TenNguoidung).ToList().ToPagedList(page, pagesize);
                return View(data);
            }
        }

        [HttpGet]
        public IActionResult UpdateNguoiDung(int MaNguoidung) 
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            List<ThongTinNguoiDung> thongtins = new List<ThongTinNguoiDung>();
            var data = context.ThongTinNguoiDungs.FromSqlRaw("Exec ThongTin_NguoiDung").ToList();
            thongtins = data;

            ThongTinNguoiDung? MaId = thongtins.Find(
                (ThongTinNguoiDung ob) => { return (ob.MaNguoidung == MaNguoidung); }    //tìm đối tượng trong list
            );

            var data_dep = context.ChucVus.ToList();
            ViewBag.depar_data = data_dep;

            if ( MaId != null )
            {
                var tt = new ThongTinNguoiDung()
                {
                    MaNguoidung = MaId.MaNguoidung,
                    Username = MaId.Username,
                    Password = MaId.Password,
                    TenNguoidung = MaId.TenNguoidung,
                    Gioitinh = MaId.Gioitinh,
                    Chucvu = MaId.Chucvu,
                    SodienthoaiNv = MaId.SodienthoaiNv,
                    DiachiNv = MaId.DiachiNv,
                    MaChucvu = MaId.MaChucvu,
                };
                return View(tt);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]

        public async Task<IActionResult> UpdateNguoiDung(Nguoidung emp)
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            var employeeId = await context.Nguoidungs.FindAsync(emp.MaNguoidung);
            if (employeeId != null)
            {
                employeeId.MaNguoidung = emp.MaNguoidung;
                employeeId.Username = emp.Username;
                employeeId.Password = emp.Password;
                employeeId.TenNguoidung = emp.TenNguoidung;
                employeeId.Gioitinh = emp.Gioitinh;
                employeeId.MaChucvu = emp.MaChucvu;
                
                employeeId.DiachiNv = emp.DiachiNv;

                if (emp.SodienthoaiNv == null)
                {
                    await Response.WriteAsync("<script>alert('Check Again !!!');window.location = 'UpdateNguoiDung';</script>");
                    return View();
                }
                else
                {
                    employeeId.SodienthoaiNv = emp.SodienthoaiNv;
                    await context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                
            }

            return View();
        }

        public async Task<IActionResult> DeleteNguoiDung(int MaNguoidung)
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            var delEmp = await context.Nguoidungs.FindAsync(MaNguoidung);
            if (delEmp != null)
            {

                await context.Database.ExecuteSqlRawAsync("EXEC Xoa_NguoiDung {0}", MaNguoidung);
                await Response.WriteAsync("<script>alert('Delete Successfully !!!');window.location = 'Index';</script>");
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult ADDNguoiDung()
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            var data = context.ChucVus.ToList();
            ViewBag.depar_data = data;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ADDNguoiDung(Nguoidung ngd)
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                List<Nguoidung> data = context.Nguoidungs.ToList();

                foreach (var tk in data)
                {
                    if (ngd.Username == tk.Username)
                    {
                        await Response.WriteAsync("<script>alert('USERNAME existed');window.location = 'ADDNguoiDung';</script>");
                        return View();
                    }
                }
                await context.Nguoidungs.AddAsync(ngd);
                await context.SaveChangesAsync();
                await Response.WriteAsync("<script>alert('Created Successfully !!!');window.location.assign('../NguoiDung/Index');</script>");
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpGet]
        public IActionResult LichSu(int Ma_Nguoidung)
        {
            var da = context.HienThiYeuCaus.FromSqlRaw("YeuCauKH").ToList();
            ViewBag.YC = da.ToList();
            var data = context.LichSuMuaHangs.FromSqlRaw("EXEC LichSuMH {0}",Ma_Nguoidung).ToList();

            var data1 = context.HienThiHoaDons.FromSqlRaw("HD_DaGiao").ToList();
            List<HienThiHoaDon> hd = new List<HienThiHoaDon>();
            hd = data1;

            var tt = hd.Where(x=>x.MaKhachhang==Ma_Nguoidung).FirstOrDefault();
            ViewBag.ThongTin = tt;

            return View(data);
        }


    }
}

Views/NguoiDung/ADDNguoiDung.cshtml
@model QuanLyBanGiay_ADMIN.Models.Nguoidung

@{
    ViewData["Title"] = "DangKy";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<!--================Login Box Area =================-->

<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-info">Tạo tài khoản mới</h2>
                </div>
                <div class="card-body">
                    <form asp-action="ADDNguoiDung" method="post">
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="us" name="Username" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'" onkeyup="checkuser()">
                            <span class="text-danger" asp-validation-for="Username" id="user"></span>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="pw" name="Password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'" onkeyup="checkpass()">
                            <span class="text-danger" asp-validation-for="Password" id="pass"></span>
                        </div>
                        <div class="col-md-12 form-group">
                            <input style="text-transform: capitalize;" type="text" class="form-control" id="tennd" asp-for="TenNguoidung" placeholder="Tên người dùng" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tên người dùng'" onkeyup="checkten()">
                            <span class="text-danger" asp-validation-for="TenNguoidung" id="tennd_err"></span>
                        </div>
                        <div class="form-group">
                            <select asp-for="Gioitinh" id="name" class="form-select form-select-lg mb-3 form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Giới tính'">
                                <option selected>Giới tính</option>
                                <option value="Nam">Nam</option>
                                <option value="Nữ">Nữ</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <select asp-for="MaChucvu" id="name" class="form-select form-select-lg mb-3 form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Mã chức vụ'">
                                <option selected>Chức vụ</option>
                                <option value="1">Nhân viên</option>
                                <option value="2">Khách hàng</option>
                            </select>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="number" class="form-control" id="sdt" asp-for="SodienthoaiNv" placeholder="Số điện thoại" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Số điện thoại'" onkeyup="checksdt()">
                            <span class="text-danger" asp-validation-for="SodienthoaiNv" id="sdt_err"></span>
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="dc" asp-for="DiachiNv" placeholder="Địa chỉ" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Địa chỉ'" onkeyup="checkdiachi()">
                            <span class="text-danger" asp-validation-for="DiachiNv" id="dc_err"></span>
                        </div>
                        <div class="">
                            <button onclick="ThongBao()" type="submit" value="submit" class="primary-btn bg-danger">CREATE A NEW ACCOUNT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function ThongBao() {
        var us = document.getElementById("us").value;
        var pw = document.getElementById("pw").value;
        var tennd = document.getElementById("tennd");
        var sdt = document.getElementById("sdt");
        var dc = document.getElementById("dc").value;
        if (us == "" || pw == "" || tennd.value == "" || sdt == "" || dc == "" || /\d/.test(tennd.value) == true || /(84|0[3|5|7|8|9])+([0-9]{8})\b/.test(sdt.value) == false) {
            tennd.value = "";
            tennd.innerText = tennd.value;

            sdt.value = "";
            sdt.innerText = sdt.value;
        }
        else {
            window.alert("Người dùng " + tennd.value + " đang được tạo ...");
        }

    }
    function checkuser() {
        var us = document.getElementById("us");
        var us_span = document.getElementById("user");
        us_span.innerHTML = "";
    }
    function checkpass() {
        var pw = document.getElementById("pw");
        var ps_span = document.getElementById("pass");
        ps_span.innerHTML = "";
    }
    function checkten() {
        var tennd = document.getElementById("tennd");
        var tennd_err = document.getElementById("tennd_err");
        tennd_err.innerHTML = "";
        if (/\d/.test(tennd.value) == true) {
            tennd_err.innerHTML = "Sai định dạng";
        } else {
            tennd_err.innerHTML = "";
        }
    }
    function checksdt() {
        var sdt = document.getElementById("sdt");
        var sdt_err = document.getElementById("sdt_err");
        sdt_err.innerHTML = "";
        if (/(84|0[3|5|7|8|9])+([0-9]{8})\b/.test(sdt.value) == false) {
            sdt_err.innerHTML = "Số điện thoại không hợp lệ";
        } else {
            sdt_err.innerHTML = "";
        }
    }
    function checkdiachi() {
        var dc = document.getElementById("dc");
        var dc_err = document.getElementById("dc_err");
        dc_err.innerHTML = "";
    }

</script>

Views/NguoiDung/Index.cshtml
@model X.PagedList.IPagedList<QuanLyBanGiay_ADMIN.Models.ThongTinNguoiDung>
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .table td, .table th {
        padding: 0.75rem;
        vertical-align: middle;
        border-top: 1px solid #dee2e6;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-12 offset">
            <h1 class="text-info text-center p-1 border border-dark">TÀI KHOẢN NGƯỜI DÙNG</h1>
            <form action="~/NguoiDung/Index" method="post">
                <div class="form-group">
                    <input type="Text" id="enter" name="TenNguoidung" placeholder="enter here">
                    <input type="submit" class="btn btn-sm btn-warning m-1 p-1 text-light" value="Search"><br />
                </div><hr />
            </form>
            <table class="table table-bordered text-center">
                <thead class="bg-dark text-light">
                    <tr>
                        <th>Mã người dùng</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Tên người dùng</th>
                        <th>Giới tính</th>
                        <th>Chức vụ</th>
                        <th>Số điện thoại</th>
                        <th>Địa chỉ</th>
                        <th colspan="2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var d in Model)
                    {
                        <tr>
                            <td>@d.MaNguoidung</td>
                            <td>@d.Username</td>
                            <td>@d.Password</td>
                            <td>@d.TenNguoidung</td>
                            <td>@d.Gioitinh</td>
                            <td>@d.Chucvu</td>
                            <td>@d.SodienthoaiNv</td>
                            <td>@d.DiachiNv</td>
                            <td>
                                <a class="btn btn-sn btn-primary" asp-action="UpdateNguoiDung" asp-controller="NguoiDung" asp-route-MaNguoidung="@d.MaNguoidung">Details</a>
                            </td>
                            <td>
                                <a class="btn btn-sn btn-warning" asp-action="LichSu" asp-controller="NguoiDung" asp-route-Ma_Nguoidung="@d.MaNguoidung">History</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        </div>
    </div>
</div>
<div class="page-info" style="text-align:center">
    Trang @(Model.PageNumber) trên @Model.PageCount
</div>
<div class="card-tools">
    <ul class="pagination pagination-sm">
        @Html.PagedListPager(Model,page=>Url.Action("Index","NguoiDung",new{page = page,TenNguoidung = ViewBag.TenND}), new PagedListRenderOptions{
        LiElementClasses = new string[] {"page-item"},
        PageClasses = new string[] {"page-link"},
        Display = PagedListDisplayMode.IfNeeded,
        MaximumPageNumbersToDisplay = 3, // Số trang tối đa để hiển thị
        EllipsesFormat = "&#8230;", // Định dạng dấu ba chấm
        })

    </ul>
</div>

Views/NguoiDung/LichSu.cshtml
@model IEnumerable<QuanLyBanGiay_ADMIN.Models.LichSuMuaHang>

@{
    ViewData["Title"] = "LichSu";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@{
    string lastMaHoadon = null;
    decimal totalThanhtien = 0;
}

@if (ViewBag.ThongTin!=null)
{
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-20 offset">
                    <div class="callout callout-info">
                        <h3 style="color:red">LỊCH SỬ MUA HÀNG </h3>
                        <div class="invoice p-3 mb-3">
                            <div class="row invoice-info">
                                <address>
                                    <strong>Thông tin khách hàng</strong><br>
                                    Tên khách hàng: @ViewBag.ThongTin.TenNguoidung<br>
                                    Số điện thoại: @ViewBag.ThongTin.sdt<br>
                                </address>
                            </div>
                        </div>
                        <div class="row">
                            <table id="lst" class="table table-bordered text-center">
                                <thead class="bg-dark text-light">

                                    <tr>
                                        <th>Mã hóa đơn</th>
                                        <th>Mã sản phẩm</th>
                                        <th>Tên sản phẩm</th>
                                        <th>Ngày đặt hàng</th>
                                        <th colspan="3">Ảnh sản phẩm</th>
                                        <th>Size</th>
                                        <th>Số lượng</th>
                                        <th>Giá gốc</th>
                                        <th>Mã giảm giá</th>
                                        <th>Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var d in Model)
                                    {
                                        if (lastMaHoadon != null && lastMaHoadon == d.MaHoadon)
                                        {

                                            // Đây là các dòng tiếp theo cho cùng một "MaHoadon"
                                            <tr>
                                                <td class="text-center"></td> <!-- Không hiển thị MaHoadon lần thứ 2 trở đi -->
                                                <td>@d.MaSanpham</td>
                                                <td>@d.Ten_Sanpham</td>
                                                <td>@string.Format("{0:dd/MM/yyyy}",d.Ngaydathang)</td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link1" />
                                                </td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link2" />
                                                </td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link3" />
                                                </td>
                                                <td>@d.size</td>
                                                <td>@d.Soluong</td>
                                                <td>@string.Format("{0:N0}", d.Giagoc)</td>
                                                <td>@d.MaGiamgia</td>
                                                <td>
                                                    @string.Format("{0:N0}", d.Thanhtien)
                                                </td>
                                            </tr>

                                            // Cập nhật tổng thành tiền
                                            totalThanhtien = (decimal)(totalThanhtien + (decimal?)d.Thanhtien);
                                        }
                                        else
                                        {
                                            // Đây là dòng đầu tiên cho mỗi "MaHoadon"
                                            <tr>
                                                <td>@d.MaHoadon</td>
                                                <td>@d.MaSanpham</td>
                                                <td>@d.Ten_Sanpham</td>
                                                <td>@string.Format("{0:dd/MM/yyyy}",d.Ngaydathang)</td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link1" />
                                                </td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link2" />
                                                </td>
                                                <td>
                                                    <img class="product-image" src="~/img/product/@d.Link3" />
                                                </td>
                                                <td>@d.size</td>
                                                <td>@d.Soluong</td>
                                                <td>@string.Format("{0:N0}", d.Giagoc)</td>
                                                <td>@d.MaGiamgia</td>
                                                <td>
                                                    @string.Format("{0:N0}", d.Thanhtien)
                                                </td>

                                            </tr>
                                            totalThanhtien = (decimal)(totalThanhtien + (decimal?)d.Thanhtien);
                                            // Cập nhật MaHoadon cuối cùng
                                            lastMaHoadon = d.MaHoadon;
                                        }
                                    }

                                    @if (lastMaHoadon != null)
                                    {
                                        <tr>
                                            <td colspan="11">Tổng tiền đã mua</td>
                                            <td>@string.Format("{0:N0}", totalThanhtien)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
    </section>
}
else
{
    <p class="text-center">TRỐNG</p>
}

Views/NguoiDung/UpdateNguoiDung.cshtml
@model QuanLyBanGiay_ADMIN.Models.ThongTinNguoiDung
@{
    ViewData["Title"] = "UpdateNguoiDung";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-info">Update Tài Khoản</h2>
                    <a href="~/NguoiDung/Index"><u style="color: blue">Back to List</u></a>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="UpdateNguoiDung">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Mã người dùng</label>
                            <input type="text" class="form-control" asp-for="MaNguoidung" readonly>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Username</label>
                            <input type="text" class="form-control" asp-for="Username" readonly>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Password</label>
                            <input type="text" class="form-control" asp-for="Password">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên người dùng</label>
                            <input type="text" class="form-control" asp-for="TenNguoidung">
                        </div>
                        <div class="form-group">
                            <select asp-for="Gioitinh" id="name" class="form-select form-select-lg mb-3 form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Giới tính'">
                                <option selected>Giới tính</option>
                                <option value="Nam">Nam</option>
                                <option value="Nữ">Nữ</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Chức vụ</label>
                            @Html.DropDownList( "MaChucvu", new SelectList( ViewBag.depar_data,"MaChucvu","TenChucVu") )
                            
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Số điện thoại</label>
                            <input type="number" id="sdt" class="form-control" asp-for="SodienthoaiNv">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Địa chỉ</label>
                            <input type="text" class="form-control" asp-for="DiachiNv">
                        </div>
                        <br />
                        <button type="submit" class="btn btn-primary" onclick="ThongBao()">SAVE</button>
                        <button type="submit" class="btn btn-primary" style="background-color:red" asp-action="DeleteNguoiDung" asp-controller="NguoiDung">Delete</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function ThongBao() {
        var sdt = document.getElementById("sdt");
        if ( /(84|0[3|5|7|8|9])+([0-9]{8})\b/.test(sdt.value) == false) {
            sdt.value = "";
            sdt.innerText = sdt.value;
            window.alert("Kiểm tra lại thông tin thay đổi !!!")
        }
        else {
            window.alert("Lưu thành công !!!");
        }

    }
</script>